import React from 'react';
import {
  Document,
  Page,
  Text,
  Image,
  StyleSheet,
} from '@react-pdf/renderer';

// Create styles
const styles = StyleSheet.create({
  body: {
    paddingTop: 35,
    paddingBottom: 45,
    paddingHorizontal: 35,
  },
  title: {
    fontSize: 24,
    textAlign: 'center',
  },
  author: {
    fontSize: 12,
    textAlign: 'center',
    marginBottom: 40,
  },
  subtitle: {
    fontSize: 16,
    margin: 12,
  },
  text: {
    margin: 12,
    fontSize: 12,
    textAlign: 'justify',
  },
  image: {
    height: 150,
    marginBottom: 30,
    marginHorizontal: 100,
  },
  header: {
    fontSize: 12,
    color: 'grey',
    marginBottom: 15,
    textAlign: 'center',
  },
  footer: {
    position: 'absolute',
    fontSize: 12,
    bottom: 25,
    left: 35,
    right: 0,
    textAlign: 'center',
    color: 'grey',
  },
});

// Create Document Component
const MyDocument = (props) => (
  <Document title="Vicode Media">
  <Page style={styles.body} wrap>
    <Text style={styles.header} fixed>
      Generated by Vicode Media
    </Text>
    <Text style={styles.title}>{props.title}</Text>
    <Image
      style={styles.image}
      src={props.image}
    />
    <Text style={styles.text}>
      {props.content}
    </Text>
    <Text
      style={styles.footer}
      render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
      fixed
    />
  </Page>
</Document>
);

export default MyDocument;